use chrono_tz::America::Toronto;
use nemembory::{ AgentPersistence, data::agents::{ Agent, DbAgentStore } };

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let db_url = "postgres://myuser:mypassword@localhost:5432/nemembory"; // Connection details from docker-compose.yml
    let todays_date = chrono::Utc::now().with_timezone(&Toronto);
    let db_store = DbAgentStore::new(db_url).await?;
    let preamble =
        format!(r#"
            # Goal:
            You are an assistant here to help the user select which tool is most appropriate to perform the task specified by the user.
            Follow these instructions closely.
            1. Consider the user's request carefully and identify the core elements of the request.
            2. Select which tool among those made available to you is appropriate given the context.
            3. This is very important: never perform the operation yourself.
            
            # Context: 
            Todays date is: {}"#, todays_date);
    let new_agent = Agent {
        id: 0, // ID will be auto-generated by the database
        code: "dummy_code".to_string(),
        display_name: "Dummy Agent".to_string(),
        system_prompt: preamble,
    };

    match db_store.add_agent(new_agent).await {
        Ok(agent) => println!("Agent added successfully: {:?}", agent),
        Err(e) => eprintln!("Failed to add agent: {}", e),
    }

    Ok(())
}
